---
  - name: rhce question 35
    hosts: ans-lab
    become: true

    tasks:
      - name: create apache group
        group:
          name: apache
          state: present 

      - name: create webdev user
        user:
          name: webdev
          group: apache
          state: present

      - name: create dir webdev
        file:
          path: /webdev
          group: apache
          mode: 2755
          state: directory


      - name:  remove httpd
        yum:
          name: httpd
          state: absent

      - name: install apache
        yum:
          name: httpd
          state: present
 
      - name: enable httpd service
        service:
          name: httpd
          state: started

      - name: create symlink
        file:
           src: /web/dev
           dest: /var/www/html/webdev
           state: link

      - name:  create the index
        copy:
          content: "development"
          dest: /webdev/index.html
